In [1]:
import torch
import torch.nn as nn

In [6]:
x = torch.arange(24, dtype= torch.float32).reshape(2, 3, 2, 2)

In [10]:
ln1 = nn.LayerNorm((3, 2, 2))
ln2 = nn.LayerNorm((2, 2))
ln3 = nn.LayerNorm(2)

In [9]:
y1, y2, y3 = ln1(x), ln2(x), ln3(x)

In [8]:
y1, y2, y3

(tensor([[[[-1.5933, -1.3036],
           [-1.0139, -0.7242]],
 
          [[-0.4345, -0.1448],
           [ 0.1448,  0.4345]],
 
          [[ 0.7242,  1.0139],
           [ 1.3036,  1.5933]]],
 
 
         [[[-1.5933, -1.3036],
           [-1.0139, -0.7242]],
 
          [[-0.4345, -0.1448],
           [ 0.1448,  0.4345]],
 
          [[ 0.7242,  1.0139],
           [ 1.3036,  1.5933]]]], grad_fn=<NativeLayerNormBackward>),
 tensor([[[[-1.3416, -0.4472],
           [ 0.4472,  1.3416]],
 
          [[-1.3416, -0.4472],
           [ 0.4472,  1.3416]],
 
          [[-1.3416, -0.4472],
           [ 0.4472,  1.3416]]],
 
 
         [[[-1.3416, -0.4472],
           [ 0.4472,  1.3416]],
 
          [[-1.3416, -0.4472],
           [ 0.4472,  1.3416]],
 
          [[-1.3416, -0.4472],
           [ 0.4472,  1.3416]]]], grad_fn=<NativeLayerNormBackward>),
 tensor([[[[-1.0000,  1.0000],
           [-1.0000,  1.0000]],
 
          [[-1.0000,  1.0000],
           [-1.0000,  1.0000]],
 
          [[

In [13]:
ln4 = nn.LayerNorm((2, 3, 2, 2))
ln4(x)

tensor([[[[-1.6613, -1.5169],
          [-1.3724, -1.2279]],

         [[-1.0835, -0.9390],
          [-0.7945, -0.6501]],

         [[-0.5056, -0.3612],
          [-0.2167, -0.0722]]],


        [[[ 0.0722,  0.2167],
          [ 0.3612,  0.5056]],

         [[ 0.6501,  0.7945],
          [ 0.9390,  1.0835]],

         [[ 1.2279,  1.3724],
          [ 1.5169,  1.6613]]]], grad_fn=<NativeLayerNormBackward>)

In [40]:
bn1 = nn.BatchNorm1d(4)

bn2 = nn.BatchNorm2d(3)

In [38]:
x.shape, bn2(x)

(torch.Size([2, 3, 2, 2]),
 tensor([[[[-1.2288, -1.0650],
           [-0.9012, -0.7373]],
 
          [[-1.2288, -1.0650],
           [-0.9012, -0.7373]],
 
          [[-1.2288, -1.0650],
           [-0.9012, -0.7373]]],
 
 
         [[[ 0.7373,  0.9012],
           [ 1.0650,  1.2288]],
 
          [[ 0.7373,  0.9012],
           [ 1.0650,  1.2288]],
 
          [[ 0.7373,  0.9012],
           [ 1.0650,  1.2288]]]], grad_fn=<NativeBatchNormBackward>))

In [51]:
x2 = torch.arange(24, dtype=torch.float32).reshape(2, 4, 3)
# x2.shape[0]
print(x2.mean((0, 2)).shape)
print(x2.mean((0, 2)))
meanV = x2.sum(-1).sum(0) / (x2.shape[0]*x2.shape[-1])
print(meanV.shape)
print(meanV)
stdV = x2.std((0, 2))
print(stdV.shape)
(x2 - meanV.reshape(-1, 1)) / stdV.reshape(-1, 1)

# x2, bn1(x2)


torch.Size([4])
tensor([ 7., 10., 13., 16.])
torch.Size([4])
tensor([ 7., 10., 13., 16.])
torch.Size([4])


tensor([[[-1.0553, -0.9045, -0.7538],
         [-1.0553, -0.9045, -0.7538],
         [-1.0553, -0.9045, -0.7538],
         [-1.0553, -0.9045, -0.7538]],

        [[ 0.7538,  0.9045,  1.0553],
         [ 0.7538,  0.9045,  1.0553],
         [ 0.7538,  0.9045,  1.0553],
         [ 0.7538,  0.9045,  1.0553]]])

In [52]:
print(bn1(x2))

tensor([[[-1.1560, -0.9909, -0.8257],
         [-1.1560, -0.9909, -0.8257],
         [-1.1560, -0.9909, -0.8257],
         [-1.1560, -0.9909, -0.8257]],

        [[ 0.8257,  0.9909,  1.1560],
         [ 0.8257,  0.9909,  1.1560],
         [ 0.8257,  0.9909,  1.1560],
         [ 0.8257,  0.9909,  1.1560]]], grad_fn=<NativeBatchNormBackward>)
